version: 2
nav:
    - 介绍:
      - 介绍: Introduction.md
    - 快速入门和速查表:
      - Musicpy快速入门和速查表: Musicpy Quickstart and Cheat Sheet.md
    - 数据结构:
      - Musicpy的数据结构: Data Structures of musicpy.md
    - 基本语法:
      - 音符类型的基本语法: Basic syntax of note type.md
      - 和弦类型的基本语法: Basic syntax of chord type.md
      - 音阶类型的基本语法: Basic syntax of scale type.md
      - 乐曲类型的基本语法: Basic syntax of piece type.md
      - 音轨类型的基本语法: Basic syntax of track type.md
      - 速度类型的基本语法: Basic syntax of tempo type.md
      - 弯音类型的基本语法: Basic syntax of pitch_bend type.md
      - 声相类型的基本语法: Basic syntax of pan type.md
      - 音量类型的基本语法: Basic syntax of volume type.md
      - 鼓点类型的基本语法: Basic syntax of drum type.md
      - 节奏类型的基本语法: Basic syntax of rhythm type.md
    - 实用的功能:
      - 实用的功能: Useful functionality.md
    - 作曲代码示例:
      - 作曲代码示例（第一期）: Musicpy composition code examples part 1.md
      - 作曲代码示例（第二期）: Musicpy composition code examples part 2.md
      - 作曲代码示例（第三期）: Musicpy composition code examples part 3.md
    - 宿主模块:
      - Musicpy宿主模块: Musicpy daw module.md
      - Musicpy宿主模块作曲代码示例: Musicpy daw module composition code examples.md
    - 算法:
      - Musicpy algorithms 模块介绍: Introduction of musicpy algorithms module.md
      - 从一首完整的钢琴曲里提取主旋律以及所有和弦的算法: The algorithm to split the main melody and chords from a piece of music.md
      - 按照乐理逻辑判断任意一组音组成的和弦类型的算法: The algorithm to determine the chord type of any group of notes according to the logic of music theory.md
    - 常见的问题:
      - 常见的问题: Frequently Asked Questions.md
theme:
  name: mkdocs
build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
mkdocs:
  configuration: mkdocs.yml