site_name: Musicpy
site_url: https://github.com/Rainbow-Dreamer/musicpy
nav:
    - Introduction:
      - Introduction: Introduction.md
    - Data Structures:
      - Data structures of musicpy: Data Structures of musicpy.md
    - Basic Syntax:
      - Basic syntax of note type: Basic syntax of note type.md
      - Basic syntax of chord type: Basic syntax of chord type.md
      - Basic syntax of scale type: Basic syntax of scale type.md
      - Basic syntax of piece type: Basic syntax of piece type.md
      - Basic syntax of track type: Basic syntax of track type.md
      - Basic syntax of tempo type: Basic syntax of tempo type.md
      - Basic syntax of pitch_bend type: Basic syntax of pitch_bend type.md
      - Basic syntax of pan type: Basic syntax of pan type.md
      - Basic syntax of volume type: Basic syntax of volume type.md
      - Basic syntax of drum type: Basic syntax of drum type.md
    - Useful functionality:
      - Useful functionality: Useful functionality.md
    - Composition Examples:
      - composition code examples Part 1: musicpy composition code examples part 1.md
      - composition code examples Part 2: musicpy composition code examples part 2.md
      - composition code examples Part 3: musicpy composition code examples part 3.md
    - Sampler Module:
      - Musicpy sampler module: musicpy sampler module.md
      - musicpy sampler module composition code examples: musicpy sampler module composition code examples.md
    - Algorithms:
      - Introduction of musicpy algorithms module: Introduction of musicpy algorithms module.md
      - the algorithm to split the main melody and chords from a piece of music: the algorithm to split the main melody and chords from a piece of music.md
      - the algorithm to determine the chord type of any group of notes according to the logic of music theory: the algorithm to determine the chord type of any group of notes according to the logic of music theory.md
    - Frequently Asked Questions:
      - Frequently Asked Questions: Frequently Asked Questions.md
theme:
  name: readthedocs
